import 'package:flutter/material.dart';
const Color blackColorOnboard = Color(0xff020518);
const Color primaryBlueColor = Color(0xff0047B3);
const Color lightBlueColor = Color(0xffEEF2F6);
const Color grayColor = Color(0xff9093AC); 
const Color blueTextColor = Color(0xff193073);
const Color secoundaryBlueColor = Color(0xff0065FF);
const Color grayEdgeFrameColor = Color(0xff929194);
const Color secoundaryTextColor = Color(0xffa0a0a0);
const Color secoundaryButtonColor = Color(0xffE1DFDF);
const Color darkBackgroundColor = Color(0xff616367);
