// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsJPSWOqH-Ablx20I7lssWTT39RsDeK1c',
    appId: '1:176414907816:android:8b9d228cef27c8859a519d',
    messagingSenderId: '176414907816',
    projectId: 'skini-cuy',
    storageBucket: 'skini-cuy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuZUwsTHaC74sEIKUoSfGpVQlrOc0X2yM',
    appId: '1:176414907816:ios:0b741b85030c024a9a519d',
    messagingSenderId: '176414907816',
    projectId: 'skini-cuy',
    storageBucket: 'skini-cuy.firebasestorage.app',
    iosClientId: '176414907816-l3f8vop73no2uq37v9oluukpnhkfd57k.apps.googleusercontent.com',
    iosBundleId: 'com.example.skinisense',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9LJ8AI2EROiTfPy_O94z-xG5g2KnCizU',
    appId: '1:648977170225:web:3d4dad7f5be58c2c6b7a10',
    messagingSenderId: '648977170225',
    projectId: 'skini-b108e',
    authDomain: 'skini-b108e.firebaseapp.com',
    storageBucket: 'skini-b108e.firebasestorage.app',
    measurementId: 'G-D33MLMNM23',
  );

}